config/routes.rb
Rails.application.routes.draw do

  resources :user_stocks, only: [:create, :destroy]
  get 'users/my_portfolio'
  devise_for :users
  root'welcome#about'
  get 'about', to: 'welcome#about'
  get 'welcome/index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]

  
end

app/views/friends/_list.html.erb
<div class="row">
   <div class="col-9">  
     <table class="table table-bordered table-hover">
       <thead>
         <tr>
           <th scope="col">Email</th>
           <th scope="col">First Name</th>
           <th scope="col">Last Name</th>
           <th scope="col">Actions</th>
         </tr>
       </thead>
       <tbody>
         <% @friends.each do |friend| %>
           <tr>
             <td><%= friend.email %></td>
             <td><%= friend.first_name %></td>
             <td><%= friend.last_name %></td>
             <td><%= link_to "View #{friend.first_name}'s profile", user_path(friend), 
                                           class: "btn btn-sm btn-secondary" %>
             <%= link_to "Stop following #{friend.first_name}", friendship_path(friend), method: :delete, data: {confirm: 'Are you sure?'},
                                           class: "btn btn-sm btn-dark" %></td>
           </tr>
         <% end %>
       </tbody>
     </table>
   </div>
 </div>