config/routes.rb
Rails.application.routes.draw do

  resources :user_stocks, only: [:create, :destroy]
  get 'users/my_portfolio'
  devise_for :users
  root'welcome#about'
  get 'about', to: 'welcome#about'
  get 'welcome/index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]

  
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol) #ticker_symbol is self created..
    client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
                                  endpoint: 'https://sandbox.iexapis.com/v1') # This is used in the free version
      #endpoint: 'https://cloud.iexapis.com/v1' -- This is the paid version
    
    #client.price(ticker_symbol)  #This is what is returned
    begin # begin and rescue are used to call to the API to see if a value exists if not we can alert that no value exists
    new(ticker: ticker_symbol, name: client.company(ticker_symbol).company_name, last_price: client.price(ticker_symbol))
    # client.company / company_name / client.price are methods taken from the 'iex-ruby-client' gem document
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    #where(ticker: "GOOG").first This method will only be specific to Google, To make more dynamic I used the method below:
    where(ticker: ticker_symbol).first
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

    def search
      if params[:stock]. present? # This will give an alert if No Ticker symbol is entered..
        @stock = Stock.new_lookup(params[:stock])
        if @stock # This will check to see (As in model if a stock value exists)
          #render json: @stock (shows view in JSON format)
          #render 'users/my_portfolio' (This renders in HTML using _result.html.erb and reloads the page but we need to format this in JS )
          respond_to do |format|
            format.js { render partial: 'users/result' } # (This renders in JS using _result.js.erb)
          end
        else
          #flash[:alert] = "Please enter a valid symbol to search" (This renders the response in HTML and reloads the page)
          respond_to do |format|
            flash.now[:alert] = "Please enter a valid symbol to search"
            format.js { render partial: 'users/result' } # (This renders in JS using _result.js.erb)
          end
          #redirect_to my_portfolio_path
        end
      else
        #flash[:alert] = "Please enter a Symbol to search" (This Renders in HTML and has the page reloaded)
        #redirect_to my_portfolio_path
        respond_to do |format|
          flash.now[:alert] = "Please enter a Symbol to search"
          format.js { render partial: 'users/result' } # (This renders in JS using _result.js.erb)
        end
      end

    end


end

app/views/stocks/_list.html.erb
<% if !@tracked_stocks.empty? %>
  <table class="table table-bordered table-hover col-sm-9">
    <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td>
              <% if current_user.can_track_stock?(stock.ticker) %> <!-- can_track_stock is a method created in the model file -->
              <%= link_to "Add to Portfolio", user_stocks_path(user: current_user, ticker: stock.ticker), class: "btn btn-sm btn-outline-secondary", method: :post %>
              <% elsif current_user.id != @user.id %>
                <span class="badge badge-danger">
                  You are tracking
                  <% if !current_user.under_stock_limit? %> <!-- Remember these methods come from the User Model -->
                    10 Stocks!
                  <% end %>
                  <% if current_user.stock_already_tracked?(stock.ticker) %>
                    this stock!
                  <% end %>
                </span>
              <% end %>
            
            <% if current_user.id == @user.id%>
              <%= link_to 'Remove', user_stock_path(stock) , method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-sm btn-outline-dark small-button' %>
            <% end %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <h3><%= current_user.full_name %>! You don't seem to be Tracking any Stocks...</h3>
    </tbody>
  </table>
<% end %>