config/routes.rb
Rails.application.routes.draw do

  resources :user_stocks, only: [:create, :destroy]
  get 'users/my_portfolio'
  devise_for :users
  root'welcome#about'
  get 'about', to: 'welcome#about'
  get 'welcome/index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]

  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks, dependent: :destroy
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol) # check_db method comes from stock.rb -- Stock.check.rb is written that way because this comes from the Stock file
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name 
    return  "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous" #Alternate way of writing if else
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id]) 
    @tracked_stocks = @user.stocks
  end

  # def search 
  #   render json: params[:friend]
  # end

  def search
    if params[:friend].present?
      @friends = params[:friend].present? # This can create multiple results thus the choice to change from @friend to @friends
        @friends = User.search(params[:friend])
        @friends = current_user.except_current_user(@friends) # except_current_user from user model, This ensures that the Current User is not displayed as well + Need to pass in @friends sa an argument as it will not dispaly
        if @friends
          respond_to do |format|
            format.js { render partial: 'users/friend_result' }
          end
        else
          respond_to do |format|
            flash.now[:alert] = "User is not found.."
            format.js { render partial: 'users/friend_result' }
          end
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a friend name or email to search"
          format.js { render partial: 'users/friend_result' }
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @friends %>
   <!-- <div class="card card-header results-block"> -->
    <table class="col-md-10">
      <tbody>
        <% @friends.each do |friend| %>
          <tr class="card card-header results-block">
            <td><strong>Name: </strong> <%= friend.full_name %></td>
              <td><strong>Email: </strong> <%= friend.email %></td>
              <td></td>
              <td><%= link_to "View #{friend.first_name}'s Profile", user_path(friend),
                                            class: "btn btn-primary btn-sm " %>
              </td>
              <td><% if current_user.not_friends_with?(friend.id) %> <!-- Method "not_friends_with?" - Created in User model -->
                <%= link_to "Follow #{friend.first_name}?", friendships_path(friend: friend),
                                      class: "btn btn-sm btn-success ml-1", method: :post %><br />
                  <% else %>
                  <span class="badge badge-pill badge-warning">You are already friends</span>
                  <% end %>
              </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <!-- </div> -->
 <% end %> 

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/_result.html.erb
<div class="results-block">
  <%= render 'layouts/messages'%>
</div>

<% if @stock %>
  <div class="card card-header results-block mb-2"> <!-- This section renders the stock views below the form -->
    <strong>Symbol: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %> <!-- can_track_stock is a method created in the model file -->
      <%= link_to "Add to Portfolio", user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-sm btn-dark", method: :post %>
      <% else %>
        <span class="badge badge-danger">
          You are already tracking
          <% if !current_user.under_stock_limit? %> <!-- Remember these methods come from the User Model -->
            10 Stocks!
          <% end %>
          <% if current_user.stock_already_tracked?(@stock.ticker) %>
            this stock!
          <% end %>
        </span>
    <% end %>
    <!-- Might see an error " undefined method `ticker' for nil:NilClass " to resolve use <%# if @stock %>-->
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = "<%= j render 'users/result.html'%>" 

// j render = escapes javascript thus code will show up on portfolio page
// Another way of writing this 'escape_javascript(render 'users/result.html')'

app/views/users/my_friends.html.erb
<span class="page-title"><h1 class="center">Friends</h1></span>

<div class='search-area'>
 <span class="page-title"> <h3>Search Friends</h3></span>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-dark btn-lg ml-2" do %>
          <i class="fa fa-search "></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="friend-results">

</div>

<% if !@friends.empty? %>
  <%= render 'friends/list' %>
  <% else %>
  <h4>You have no Friends..</h4>
<% end %>

app/views/users/my_portfolio.html.erb
<span class="page-title"><h1>My Portfolio for <%= current_user.full_name %></h1></span>
<div class="search-area pt-5">
  <span class="page-title"><h3>Search Stocks</h3></span>

  <%= form_tag search_stock_path, remote: true, method: :get do %> <!-- This shows the form and the Button, remote: true sets this up as an AJAX call -->
    <div class='form-group row'>
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-dark btn-lg ml-2" do %>
           <i class="fa fa-search "></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="results">
</div>

  <% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list' %>
  <% end %>

app/views/users/show.html.erb
<h2>User Details for: <%= @user.full_name%></h2>


<div class="card card-header results-block">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Name: </strong> <%= @user.full_name %></td>
        <td><strong>Email: </strong> <%= @user.email %></td>
        <td>
          <% if current_user.not_friends_with?(@user.id) %>
            <%= link_to "Follow #{@user.first_name} ?", friendships_path(friend: @user),
                          class: "btn btn-sm btn-success", method: :post %>
          <% else %>
            <span class="badge badge-primary">
              You are friends
            </span>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>
<h3><%= @user.first_name %> is Tracking: <span class="badge badge-secondary"><%= @user.stocks.count %> Stocks</span></h3>
<% if !@tracked_stocks.empty? %>
    <%= render 'stocks/list' %>
<% else %>
  Unfortunately <%= @user.first_name %> is not currently tracking any stocks...
  <% end %>