config/routes.rb
Rails.application.routes.draw do

  resources :user_stocks, only: [:create, :destroy]
  get 'users/my_portfolio'
  devise_for :users
  root'welcome#about'
  get 'about', to: 'welcome#about'
  get 'welcome/index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]

  
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="footer">
    <div class="container text-center">
      <small class="footer-text">Created by <%= link_to "Vincent Walker", "https://vincethewalker.com", class: "footer-logo" %> 2020</small>
    </div>
  </footer>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if request.path == root_path %>">
          <%= link_to "Home", root_path, class: "btn btn-outline-secondary" %>
        </li>
        <li class="nav-item <%= 'active' if request.path == root_path %>">
          <%= link_to "About", about_path, class: "btn btn-outline-secondary ml-1" %>
        </li>
        <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
          <%= link_to "My Stock Portfolio", my_portfolio_path, class: "btn btn-outline-secondary ml-1" %>
        </li>
        <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
          <%= link_to 'My Friends', my_friends_path, class: 'btn btn-outline-secondary ml-1' %>
        </li>
        <li><span class="nav-title"><h1 class="ml-5">My Stock Market</h1></span></li>
      </ul>
    </div>
 
    
      
        <% if current_user %> 
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-dark mr-1" %>
          <span class="navi-item badge badge-dark nav-name"> 
              <i class="fa fa-user"></i> <%=  current_user.full_name  %>
          </span>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-secondary mr-1" %>
        <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StockTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv=“X-UA-Compatible” content=“IE=edge”>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Amaranth&family=Baloo+2&family=Kalam&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <div class="container">
      <%=render 'layouts/messages'%>
      <%= yield %>
    </div>
  </body>
</html>